meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
- name: h2
  templates:
  - name: h2-instance
    release: h2
  instances: 0
  resource_pool: small_z1
  networks: ((merge))
  properties:
    h2:
      port: 9001

networks: (( merge ))

properties: {}
